# defang.yaml
name: taz-uddin-traders

services:
  - name: web
    build: .
    port: 8000
    healthcheck: /
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production
      - PORT=8000
    resources:
      memory: 512
      cpu: 0.5
    
  - name: postgres
    image: postgres:15
    port: 5432
    environment:
      - POSTGRES_DB=tazuddin_db
      - POSTGRES_USER=tazuddin_user
      - POSTGRES_PASSWORD=secure_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    resources:
      memory: 512
      cpu: 0.5

volumes:
  postgres_data: