# Generated by Django 4.2.7 on 2025-10-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['user', 'status'], name='services_re_user_id_043ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['created_at'], name='services_re_created_8a3184_idx'),
        ),
    ]
